USE [master]
GO

/****** Object:  Database [DW-AdventureWorks-CWarren]    Script Date: 12/11/2016 10:22:35 PM ******/
CREATE DATABASE [DW-AdventureWorks-CWarren]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DW-AdventureWorks-CWarren', FILENAME = N'C:\_BISolutions\_BIConceptsProject\DW-AdventureWorks-CWarren.mdf' , SIZE = 20480KB , MAXSIZE = 1048576KB , FILEGROWTH = 10240KB )
 LOG ON 
( NAME = N'DW-AdventureWorks-CWarren_log', FILENAME = N'C:\_BISolutions\_BIConceptsProject\DW-AdventureWorks-CWarren_log.ldf' , SIZE = 11264KB , MAXSIZE = 1048576KB , FILEGROWTH = 10240KB )
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DW-AdventureWorks-CWarren].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET ARITHABORT OFF 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET RECOVERY BULK_LOGGED 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET  MULTI_USER 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET QUERY_STORE = OFF
GO

USE [DW-AdventureWorks-CWarren]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [DW-AdventureWorks-CWarren] SET  READ_WRITE 
GO

